# (PART) Case studies {-} 

# Identification of bushfire-specific PM~2.5~

The absolute PM~2.5~ and STL decomposition remainder can be used to indicate unusually high PM~2.5~ days (e.g. days with a remainder > 2SD of remainder). However, this does not differentiate between sources, of which dust and wood heater smoke are major contributors in Australia.

Thus, the binary flags are provided to aid in differentiating days of high PM~2.5~ due to bushfires and those due to other sources. 

The flags consist of:

- active fires within a certain buffer
    - this is derived from satellite and thus may not pick up active fires in cloudy conditions
- dust particles above a certain percentile (satellite-derived)
- temperature below a certain threshold
    - used as a proxy for likely wood heater use (the warmer the less likely wood heaters are used)
- daily PM~2.5~ above 99th percentile and remainder above 2SD
    - general indication of unusually high PM~2.5~

Some combination of the flags can thus provide an indication of whether that particular day's PM~2.5~ is likely due to firesmoke. There is no definitive rule on which combination should be used. Rather, the choice should be guided by the study question and scope. The user should also consider using any additional data available in their study region to compare with or validate the predictions of bushfire-specific smoke.

<!-- We suggest using the flags indicated by the first model described below as a starting point - this is classification and regression tree (CART) model trained using a set of known bushfire events. Following the CART model, alternative combinations of flags used previously are outlined. -->



<!-- ### Alternative 1 -->

<!-- This approach looks for exceptional daily variation in PM~2.5~ or for active fire in vicinity, using the conditionals: -->

<!-- - trimmed_smoke_2SD_v1_3 > 0, AND -->
<!-- - active_fires_50000 = 1 -->

<!-- ### Alternative 2 -->

<!-- This approach, designed for polygonal study areas rather than point locations, used the following conditions to signal a probable firesmoke day: -->

<!-- - dust_merra_2_p75 < 0.5, AND -->
<!-- - dust_cams_p75 < 0.5, AND -->
<!-- - whs_15degreeC < 0.5, AND -->
<!-- - smoke_p95 = 1 -->

<!-- The first three conditions were calculated on the mean of the raster cells within the polygon. For the fourth condition, `smoke_p95` was set to `1` if the geometric mean of PM~2.5~ within the polygon was greater than the 95th percentile of means for that polygon, calculated over the study period (in that particular case from 2010-01-01 to 2019-06-30). -->
